apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: view-secret
spec:
  version: {{ .TagName }}
  homepage: https://github.com/elsesiy/kubectl-view-secret
  shortDescription: Decode Kubernetes secrets
  description: |+2
    Base64 decode by key or all key/value pairs in a given secret.

    # print secret keys
    $ kubectl view-secret <secret>

    # decode specific entry
    $ kubectl view-secret <secret> <key>

    # decode all secret contents
    $ kubectl view-secret <secret> -a/--all

    # print keys for secret in different namespace
    $ kubectl view-secret <secret> -n/--namespace foo

    # print keys for secret in different context
    $ kubectl view-secret <secret> -c/--context ctx

    # print keys for secret by providing kubeconfig
    $ kubectl view-secret <secret> -k/--kubeconfig <cfg>

    # suppress info output
    $ kubectl view-secret <secret> -q/--quiet
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
    {{ addURIAndSha "https://github.com/elsesiy/kubectl-view-secret/releases/download/{{ .TagName }}/kubectl-view-secret_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-view-secret
    - selector:
        matchLabels:
          os: linux
          arch: amd64
    {{ addURIAndSha "https://github.com/elsesiy/kubectl-view-secret/releases/download/{{ .TagName }}/kubectl-view-secret_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
      bin: kubectl-view-secret
    - selector:
        matchLabels:
          os: windows
          arch: amd64
    {{ addURIAndSha "https://github.com/elsesiy/kubectl-view-secret/releases/download/{{ .TagName }}/kubectl-view-secret_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
      bin: kubectl-view-secret.exe
