name: ci
on:
  push:
  pull_request:
jobs:
  ci_job:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Test
      run: make test
