---
name: ci
on: [push, pull_request]
jobs:
  ci_job:
    name: test
    runs-on: ubuntu-22.04
    container:
      image: golang:1.22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: make test
      - name: Generate coverage report
        run: make test-cov
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
