---
name: ci
on:
  pull_request:
jobs:
  ci_job:
    name: test
    runs-on: ubuntu-22.04
    container:
      image: golang:1.22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: make test
